// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2qcQjzlltEDHHvZd_xGTPKBWRggvbEh0',
    appId: '1:289888933189:web:bf6492789f2076496f9a2c',
    messagingSenderId: '289888933189',
    projectId: 'dineai-pos-system',
    authDomain: 'dineai-pos-system.firebaseapp.com',
    storageBucket: 'dineai-pos-system.firebasestorage.app',
    measurementId: 'G-64X52LM83W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6yC-KfB8f_P5gZW55YooeFAvP9BT9IwY',
    appId: '1:289888933189:android:f45716d9ccd2c9876f9a2c',
    messagingSenderId: '289888933189',
    projectId: 'dineai-pos-system',
    storageBucket: 'dineai-pos-system.firebasestorage.app',
  );

  static const FirebaseOptions androidDebug = FirebaseOptions(
    apiKey: 'AIzaSyA6yC-KfB8f_P5gZW55YooeFAvP9BT9IwY',
    appId: '1:289888933189:android:f45716d9ccd2c9876f9a2c',
    messagingSenderId: '289888933189',
    projectId: 'dineai-pos-system',
    storageBucket: 'dineai-pos-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yC-KfB8f_P5gZW55YooeFAvP9BT9IwY',
    appId: '1:289888933189:ios:65869c9e1bf607b26f9a2c',
    messagingSenderId: '289888933189',
    projectId: 'dineai-pos-system',
    storageBucket: 'dineai-pos-system.firebasestorage.app',
    iosBundleId: 'com.restaurantpos.aiPosSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6yC-KfB8f_P5gZW55YooeFAvP9BT9IwY',
    appId: '1:289888933189:ios:172f92c5f656fcb16f9a2c',
    messagingSenderId: '289888933189',
    projectId: 'dineai-pos-system',
    storageBucket: 'dineai-pos-system.firebasestorage.app',
    iosBundleId: 'com.restaurantpos.aiPosSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2qcQjzlltEDHHvZd_xGTPKBWRggvbEh0',
    appId: '1:289888933189:web:d7f068f7590ee0336f9a2c',
    messagingSenderId: '289888933189',
    projectId: 'dineai-pos-system',
    authDomain: 'dineai-pos-system.firebaseapp.com',
    storageBucket: 'dineai-pos-system.firebasestorage.app',
    measurementId: 'G-64X52LM83W',
  );
} 